### PR TITLE
1.1.2 release

### PR DESCRIPTION
**Pull request by mikemhenry**
Checklist
* [ ] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by mikemhenry** [comment]
Will need to probably update some of the third_party deps

**Comment by hmacdope** [comment]
I think the main one is this: https://github.com/dmlc/dgl/tree/d40a3c37e555ff8bc6d3f84426b42d286c2556a0/third_party/HugeCTR/gpu_cache

It is not vendored as a subpackage but just as raw source as it is a snippet of a much larger library maintained by NVIDIA https://github.com/NVIDIA-Merlin/HugeCTR/blob/main/gpu_cache/ReadMe.md.

Does this make a difference as to whether we need to build as a separate package or not?  I can check if it has diverged

**Comment by mikemhenry** [comment]
In a perfect world a separate package would be nice (honestly with cuda-12 re-work I would be surprised if it wasn't a package on conda-forge (but might not work with cuda 11)) but it is more important that we include the license.

**Comment by mikemhenry** [comment]
Okay looks like the git submodules didn't change between 1.1.1 and 1.1.2 except like hugo said, `third_party/HugeCTR/gpu_cache` was added but since it wasn't done as a git submodle, the source should be in the tarball.

**Comment by mikemhenry** [comment]
The issue is it looks like there is no source file included, so that will have to be patched in

**Comment by mikemhenry** [comment]
`error: 'shared_mutex' is unavailable: introduced in macOS 10.12 - see https://conda-forge.org/docs/maintainer/knowledge_base.html#newer-c-features-with-old-sdk` okay looks like we will need to bump the osx sdk

**Comment by mikemhenry** [comment]
Okay new issue:
```
2023-09-06T21:36:46.9153365Z   ERROR (dgl,lib/python3.10/site-packages/dgl/libdgl.so): Needed DSO lib/libuv.so.1 found in ['libuv']
2023-09-06T21:36:46.9153957Z   ERROR (dgl,lib/python3.10/site-packages/dgl/libdgl.so): .. but ['libuv'] not in reqs/run, (i.e. it is overlinking) (likely) or a missing dependency (less likely)
```

and some warnings:

```
2023-09-06T21:36:46.9160670Z WARNING (dgl): run-exports library package conda-forge::libcblas-3.9.0-5_h92ddd45_netlib in requirements/run but it is not used (i.e. it is overdepending or perhaps statically linked? If that is what you want then add it to `build/ignore_run_exports`)
2023-09-06T21:36:46.9162734Z WARNING (dgl): interpreted library (Python) package conda-forge::networkx-3.1-pyhd8ed1ab_0 in requirements/run but it is not used (i.e. it is overdepending or perhaps statically linked? If that is what you want then add it to `build/ignore_run_exports`)
2023-09-06T21:36:46.9164776Z WARNING (dgl): interpreter (Python) package conda-forge::python-3.10.12-hd12c33a_0_cpython in requirements/run but it is not used (i.e. it is overdepending or perhaps statically linked? If that is what you want then add it to `build/ignore_run_exports`)
2023-09-06T21:36:46.9166882Z WARNING (dgl): run-exports library package conda-forge::numpy-1.25.2-py310ha4c1d20_0 in requirements/run but it is not used (i.e. it is overdepending or perhaps statically linked? If that is what you want then add it to `build/ignore_run_exports`)
2023-09-06T21:36:46.9167583Z WARNING (dgl): run-exports library package conda-forge::liblapacke-3.9.0-5_h92ddd45_netlib in requirements/run but it is not used (i.e. it is overdepending or perhaps statically linked? If that is what you want then add it to `build/ignore_run_exports`)
2023-09-06T21:36:46.9169977Z WARNING (dgl): run-exports library package conda-forge::liblapack-3.9.0-5_h92ddd45_netlib in requirements/run but it is not used (i.e. it is overdepending or perhaps statically linked? If that is what you want then add it to `build/ignore_run_exports`)
2023-09-06T21:36:46.9170861Z WARNING (dgl): run-exports library package conda-forge::libblas-3.9.0-5_h92ddd45_netlib in requirements/run but it is not used (i.e. it is overdepending or perhaps statically linked? If that is what you want then add it to `build/ignore_run_exports`)
```

We are close!!

**Comment by mikemhenry** [comment]
So tensor pipe needs `libuv` but we have to pull in tensorpipe as a submodule, so I think it would take too much work (@hmacdope please confirm) to make tensorpipe use `libuv` from conda-forge, so we build it.

**Comment by mikemhenry** [comment]
@jakirkham I am not sure what we should do in this situation, we probably shouldn't ship this lib, but I am not sure if we can hack the build system to link it statically.

**Comment by mikemhenry** [comment]
@conda-forge-admin, please rerender

**Comment by mikemhenry** [comment]
@conda-forge-admin, please rerender

**Comment by jakirkham** [comment]
Thanks Mike! 🙏

Sorry for the lack of reply. Was on PTO

**Pull request merged**
