### PR TITLE
Pytorch pincompatible

### LINKED ISSUE #41: Issue with libgraphbolt dynamic loading.
### Solution to issue cannot be found in the documentation.

- [X] I checked the documentation.

### Issue

I also ran into this issue with DGL 2.1.0 to do with the loader for libgraphbolt

https://discuss.dgl.ai/t/cannot-find-dgl-c-graphbolt-library/4429

### Installed packages

```shell
NA
```

### Environment info

```shell
NA
```

### PR DESCRIPTION
**Pull request by zklaus**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [x] ~Reset the build number to `0` (if the version changed)~
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

Fixes #41.

This adds a runtime requirement to ensure a compatible version of pytorch is used.

> :warning: **Warning**
> I am not completely sure about the combination of `pin_compatible` with build strings (as needed for pytorch), so a bit of iteration may be needed.

### CODE REVIEW

**Comment by zklaus** [comment]
I am happy with this now. It produces an additional pin `"pytorch >=2.3.1,<2.3.2.0a0",`, which should guarantee the right compatibility. You can download the artifact from the azure build and try it locally.
If you are happy with this too, @conda-forge/dgl, we should remove the artifact storage before merging.

**Comment by zklaus** [comment]
@conda-forge-admin, please rerender

**Comment by zklaus** [comment]
The tests are a wider conda-forge issue and hopefully will be resolved soon.

https://github.com/conda-forge/status/issues/181

**Comment by zklaus** [comment]
This is ready for review, @conda-forge/dgl

**Review by mikemhenry — APPROVED** [review]

**Comment by mikemhenry** [comment]
@zklaus 
https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=981847&view=logs&j=9c5ef928-2cd6-52e5-dbe6-9d173a7d951b&t=20c71c51-4b27-578b-485d-06ade2de1d00&l=468

something went quite wrong post merge to main

**Comment by hmacdope** [comment]
@mikemhenry @zklaus Whole of azure seems to be down rn: https://status.dev.azure.com/. We can kick it when its back up.

**Pull request merged**
