### PR TITLE
DGL v2.1.0 w/ liburing

### PR DESCRIPTION
**Pull request by zklaus**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] ~Bumped the build number (if the version is unchanged)~
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

This replaces the earlier bot PR and hence:
closes #35.

### CODE REVIEW

**Comment by zklaus** [comment]
@conda-forge-admin, please rerender

**Comment by zklaus** [comment]
The broken link check is most likely due to conda-forge/admin-requests#958. @conda-forge-admin, please restart ci.

**Comment by zklaus** [comment]
@conda-forge-admin, please rerender

**Comment by zklaus** [comment]
@conda-forge-admin, please rerender

**Comment by jakirkham** [comment]
@conda-forge-admin , please restart CI

**Comment by zklaus** [comment]
Ok, seems everything is working now, except for the Osx builds, which are blocked by https://github.com/conda-forge/tensorflow-feedstock/pull/372 or https://github.com/conda-forge/tensorflow-feedstock/pull/374.

**Comment by zklaus** [comment]
@conda-forge-admin, please rerender

**Comment by zklaus** [comment]
@conda-forge-admin, please rerender

**Comment by zklaus** [comment]
@h-vetinari, would you have any hints on what to do about those stdlib2.12 cuda builds?

**Comment by h-vetinari** [comment]
So I think what's happening is that - in a CUDA-enabled recipe - you're overriding [this big zip](https://github.com/conda-forge/conda-forge-pinning-feedstock/blob/main/recipe/conda_build_config.yaml#L157-L165), and as you're only overriding it partially (one key out of many), you need to match the length of the other keys in that zip.

I needed to do something [similar](https://github.com/conda-forge/arrow-cpp-feedstock/blob/main/recipe/conda_build_config.yaml) in arrow to override the compiler version (note, you'd need a third entry for linux because the CUDA 12 migrator adds to the length of that zip).

Perhaps an easier alternative would be to set
```
os_version:
  linux_64: cos7
```
in `conda-forge.yml` though, which should also [ensure](https://github.com/conda-forge/conda-forge-pinning-feedstock/blob/2f0e7184d3fae226281704f7af90a1025c68accf/recipe/conda_build_config.yaml#L18) that you get the newer stdlib

**Comment by zklaus** [comment]
@conda-forge-admin, please rerender

**Comment by zklaus** [comment]
Seems this is finally ready, @conda-forge/dgl :tada: However, I suggest to first merge #38, then rebase this on top of the new main and only merge after that.

**Comment by hmacdope** [comment]
Thanks so much for fixing conflicts @zklaus

**Review by hmacdope — APPROVED** [review]
LGTM

**Pull request merged**
