### PR TITLE
Update for 1.1.1

### PR DESCRIPTION
**Pull request by hmacdope**
Checklist
* [X] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [X] Bumped the build number (if the version is unchanged)
* [X] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [X] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by hmacdope** [comment]
@conda-forge-admin, please rerender

**Comment by hmacdope** [comment]
Reverting re-render as it removes swapfile fix.

**Comment by hmacdope** [comment]
@mikemhenry  hopefully ready to go.

**Comment by mikemhenry** [comment]
@hmacdope did any deps get dropped from third_party? This does look good but that is something I want to double check.

**Comment by mikemhenry** [comment]
from upstream:
> Remove several unused third-party libraries such as xbyak, tvm.

**Comment by mikemhenry** [comment]
Looks like we dropped those already since I only added third_party stuff as we needed it to build

**Comment by hmacdope** [comment]
I think only ones we didn't use were dropped so AFAIK no changes to build process.

**Comment by mikemhenry** [comment]
Sweet! Now onto 1.1.2 :)

**Pull request merged**
